//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBatch
    {
        public System.Guid strBatchID { get; set; }
        public string strCompanyName { get; set; }
        public string strBatchDescription { get; set; }
        public System.DateTime dtBatchCreated { get; set; }
        public int intCreatedByID { get; set; }
        public string strCreateByName { get; set; }
        public System.DateTime dtBatchUpdates { get; set; }
        public int intBatchStatus { get; set; }
        public System.DateTime dtPayDate { get; set; }
        public int intBatchType { get; set; }
        public int intTemplateID { get; set; }
        public Nullable<int> intPaymentStatusId { get; set; }
        public string strPaymentStatusByName { get; set; }
        public Nullable<System.DateTime> dtPaymentStatusDate { get; set; }
        public byte[] varPaymentConfirmation { get; set; }
        public string strPaymentConfirmationRptName { get; set; }
        public byte[] varCompanyPayrollSummary { get; set; }
        public string strPayrollSummaryRptName { get; set; }
        public Nullable<int> ClosedByUserID { get; set; }
        public Nullable<System.DateTime> ClosedDateTime { get; set; }
        public Nullable<int> intFederalTaxDepositScheduleId { get; set; }
        public Nullable<int> intFederalTaxDepositStatusId { get; set; }
        public Nullable<decimal> decFederalTaxDepositAmount { get; set; }
        public Nullable<System.DateTime> dtFederalTaxDepositDate { get; set; }
        public string strFederalTaxEFTPSNo { get; set; }
        public Nullable<System.DateTime> dtFederalTaxStatusDate { get; set; }
        public string strFederalTaxStatusByName { get; set; }
        public byte[] varFederalTaxConfirmation { get; set; }
        public string strFederalTaxRptName { get; set; }
        public Nullable<int> intHaciendaTaxDepositScheduleId { get; set; }
        public Nullable<int> intHaciendaTaxDepositStatusId { get; set; }
        public Nullable<decimal> decHaciendaTaxDepositAmount { get; set; }
        public Nullable<System.DateTime> dtHaciendaTaxDepositDate { get; set; }
        public string strHaciendaTaxReceiptNo { get; set; }
        public Nullable<System.DateTime> dtHaciendaTaxStatusDate { get; set; }
        public string strHaciendaTaxStatusByName { get; set; }
        public byte[] varHaciendaTaxConfirmation { get; set; }
        public string strHaciendaTaxRptName { get; set; }
        public Nullable<int> intFUTATaxDepositScheduleId { get; set; }
        public Nullable<int> intFUTATaxDepositStatusId { get; set; }
        public Nullable<decimal> decFUTATaxDepositAmount { get; set; }
        public Nullable<System.DateTime> dtFUTATaxDepositDate { get; set; }
        public string strFUTATaxReceiptNo { get; set; }
        public Nullable<System.DateTime> dtFUTATaxStatusDate { get; set; }
        public string strFUTATaxStatusByName { get; set; }
        public byte[] varFUTATaxConfirmation { get; set; }
        public string strFUTATaxRptName { get; set; }
        public int intACHSentCount { get; set; }
        public string ACHFileName { get; set; }
    }
}
